name: CiTY
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  image_picker: ^1.1.1
  geolocator: ^11.0.0
  permission_handler: ^12.0.1
  audioplayers: ^5.2.1
  
  flutter_sound: ^9.2.13
  image: ^4.1.7
  intl: ^0.19.0
  geocoding: ^2.2.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  firebase_database: ^12.0.1
  flutter_screenutil: ^5.9.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"
